### ISSUE TITLE
appdb description 

### ISSUE THREAD

**Issue by ZonD80** [sideloading/sideloading-master-guide#1]
Please update appdb's description, it became free but paid to apple, $99 per year for all devices, developer account must to be purchased directly from apple via apple developer apps

without their plus subscription they allow to sign only 30 apps per 30 days, otherwise less than $1 per month

no revokes, but expensive if you have only one device and have no friends:

You can not obtain appdb PRO anymore

Apple requires you to buy your own Developer Account, if you want to install apps not from AppStore. It costs 5x more than PRO ($99), but it will allow you to sideload apps without any issues on all your devices, and it should not be revoked. Pay to Apple, not to us. The good thing is that one account can be used across all your devices and devices of your family and friends. You don't need to buy each account for each device as it was with PRO, there is only one account for all your devices required.

We care a lot about our community. As usage of PROs has became extremely unstable, we have stopped appdb PRO program, it is not available for new users anymore. Existing PROs will continue to work until their expiration and will be reactivated in case of revocations, if there will be shared accounts available. If not, PRO will be freely upgraded to PLUS.

appdb PLUS is optional subscription that helps us to maintain appdb and keep it ad-free, pay for servers and traffic. If you feel generous and want to support appdb, please obtain appdb PLUS.

also limitations are 33 days, not 14

**Comment by sideloading** [comment]
Hey @ZonD80, thanks for clarifications. I'll work on updating information by next week.

Not sure why the changes aren't being pushed out into the repo so hopefully can fix it as well.

**Comment by sideloading** [comment]
Have made some changes with https://github.com/sideloading/sideloading-master-guide/commit/c319f2fc6f39947d0ae1cad1a23fde55b397b87d

Feel free to make a PR if you want any info changed.
